export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#444749',
        'surface-variant': '#e2e2e5',
        'surface-tint': '#5c5f61',
        'surface-container': '#edeef1',
        'tertiary-fixed': '#d8e2ff',
        'on-tertiary-fixed-variant': '#004493',
        'on-error': '#ffffff',
        'background': '#f9f9fc',
        'tertiary-container': '#002e69',
        'surface-container-low': '#f3f3f6',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#c5c7c9',
        'on-primary-container': '#96999b',
        'tertiary': '#001a41',
        'primary': '#191c1e',
        'primary-container': '#2e3133',
        'outline-variant': '#c4c7c9',
        'inverse-on-surface': '#f0f0f3',
        'on-secondary-fixed-variant': '#44474b',
        'on-surface-variant': '#444749',
        'outline': '#74777a',
        'on-surface': '#1a1c1e',
        'on-tertiary-container': '#5b96ff',
        'on-secondary-fixed': '#181c20',
        'inverse-primary': '#c5c7c9',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#c4c6cc',
        'on-tertiary-fixed': '#001a41',
        'surface-container-highest': '#e2e2e5',
        'on-primary': '#ffffff',
        'surface-bright': '#f9f9fc',
        'primary-fixed': '#e1e3e5',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#e0e2e8',
        'secondary': '#5b5f63',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e0e2e8',
        'error': '#ba1a1a',
        'on-background': '#1a1c1e',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e8e8eb',
        'surface-dim': '#d9dadd',
        'on-secondary-container': '#616569',
        'tertiary-fixed-dim': '#adc6ff',
        'inverse-surface': '#2f3133',
        'on-primary-fixed': '#191c1e',
        'surface': '#f9f9fc',
        // Aliases for common usage
        accent: '#007AFF',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0_8px_30px_rgb(0,0,0,0.04)',
        'card-hover': '0_8px_30px_rgb(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
